CREATE DATABASE  IF NOT EXISTS `carros`;
USE `carros`;

DROP TABLE IF EXISTS `concessionaria`;
CREATE TABLE `concessionaria` (
  `IDCONCESSIONARIA` smallint(6) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`IDCONCESSIONARIA`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `carro`;
CREATE TABLE `carro` (
  `IDCARRO` smallint(11) NOT NULL AUTO_INCREMENT,
  `MARCA` varchar(100) NOT NULL,
  `IDCONCESSIONARIA` smallint(6) NOT NULL,
  `FOTO` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`IDCARRO`),
  KEY `FK_CARRO_CONCESSIONARIA_idx` (`IDCONCESSIONARIA`),
  CONSTRAINT `FK_CARRO_CONCESSIONARIA` FOREIGN KEY (`IDCONCESSIONARIA`) REFERENCES `concessionaria` (`IDCONCESSIONARIA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `usuario`;
CREATE TABLE `usuario` (
  `IDUSUARIO` smallint(6) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `SENHA` varchar(100) NOT NULL,
  PRIMARY KEY (`IDUSUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `aluguel`;
CREATE TABLE `alguel` (
  `IDALUGUEL` smallint(11) NOT NULL AUTO_INCREMENT,
  `VALOR` float NOT NULL,
  `DATA` date NOT NULL,
  `IDCARRO` smallint(11) NOT NULL,
  `IDCONCESSIONARIA` smallint(6) NOT NULL,
  PRIMARY KEY (`IDALUGUEL`),
  CONSTRAINT `FK_CONCESSIONARIA_ALUGUEL` FOREIGN KEY (`IDCONCESSIONARIA`) REFERENCES `concessionaria` (`IDCONCESSIONARIA`),
  CONSTRAINT `FK_CARRO_ALUGUEL` FOREIGN KEY (`IDCARRO`) REFERENCES `carro` (`IDCARRO`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

